<?php
/**
 * Language labels for module "tools_txrsuserimpM1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'Import TYPO3 users from file',
		'function1' => 'Import Users',
		'function2' => 'Rollback Import',
		'function3' => 'Security Note',
		'f1.tab1' => 'Import File',
		'f1.tab1.description' => 'Please select an import file from your local computer. This file is supposed to hold user information in pure text format.',
		'f1.tab1.section.defaultSettings' => 'General settings',
		'f1.tab1.section.importFile' => 'Import file',
		'f1.tab1.section.importFile.currentImportFile' => 'Current file:',
		'f1.tab1.section.importFile.emptyImportFile' => '[no file choosen]',
		'f1.tab1.section.importFile.importFile' => 'Choose a file from your local computer:',
		'f1.tab1.section.importFile.overwriteFile' => 'Overwrite existing files:',
		'f1.tab1.section.loadSettings' => 'Load presets',
		'f1.tab1.section.error' => 'File upload error',
		'f1.tab1.section.error.description' => 'File upload failed, please review your user settings. Possible reasons for this error: you don\'t have access rights to the upload folder or the folder fileadmin\_temp_ does not exist. Please correct this.',
		'f1.tab2' => 'Import Settings',
		'f1.tab2.constants.BE' => 'BE (backend users)',
		'f1.tab2.constants.colon' => 'Colon [:]',
		'f1.tab2.constants.comma' => 'Comma [,]',
		'f1.tab2.constants.FE' => 'FE (frontend users)',
		'f1.tab2.constants.semicolon' => 'Semicolon [;]',
		'f1.tab2.constants.tab' => 'TAB',
		'f1.tab2.constants.TT' => 'tt_address (addresses)',
		'f1.tab2.description' => 'Please review the settings for this import process. You may also load a previously saved preset.',
		'f1.tab2.section.defaultGroup' => 'Usergroup',
		'f1.tab2.section.defaultGroup.emptyGroup' => '[ERROR: no FE usergroups]',
		'f1.tab2.section.defaultGroup.emptyGroup.error' => 'Error: Please select one or more usergroups first!',
		'f1.tab2.section.defaultGroup.label' => 'Please select a usergroup for the imported users:',
		'f1.tab2.section.generalSettings' => 'General settings',
		'f1.tab2.section.generalSettings.additionalMandatoryFields' => 'Additional Mandatory Fields',
		'f1.tab2.section.generalSettings.additionalMandatoryFields.description' => 'Please specify additional fields which <em>must</em> be present for each user you want to import [hold STRG to select multiple]:',
		'f1.tab2.section.generalSettings.enableAutoRename' => 'Enable auto-rename :',
		'f1.tab2.section.generalSettings.enableAutoValues' => 'Enable auto-values :',
		'f1.tab2.section.generalSettings.fieldDelimiter' => 'Field delimiter (data fields are separated by...):',
		'f1.tab2.section.generalSettings.fieldEncaps' => 'Field encapsulation character (data fiels are encapsed with...):',
		'f1.tab2.section.generalSettings.firstRowHasFieldnames' => 'First row of import file has fieldnames:',
		'f1.tab2.section.generalSettings.previewNum' => 'Preview lines (number of preview rows for the mapping process):',
		'f1.tab2.section.generalSettings.update' => 'Update settings:',
		'f1.tab2.section.generalSettings.update.update' => 'Update',
		'f1.tab2.section.generalSettings.userupdate' => 'Update existing users',
		'f1.tab2.section.generalSettings.userupdate.description' => 'Support updates (existing users will be updated instead of added):',
		'f1.tab2.section.presets' => 'Presets',
		'f1.tab2.section.presets.delete.deleted' => 'Preset %s [UID %s] deleted.',
		'f1.tab2.section.presets.delete.noSelection' => 'Error: No preset selected for deletion.',
		'f1.tab2.section.presets.delete.notOwner' => 'Error: You are not the owner of this preset.',
		'f1.tab2.section.presets.load' => 'Load preset:',
		'f1.tab2.section.presets.load.delete' => 'Delete',
		'f1.tab2.section.presets.load.delete.sure' => 'Do you really want to delete this preset?',
		'f1.tab2.section.presets.load.load' => 'Load',
		'f1.tab2.section.presets.load.loaded' => 'Preset %s [UID %s] loaded.',
		'f1.tab2.section.presets.load.noData' => 'Error: The preset was empty.',
		'f1.tab2.section.presets.load.noSelection' => 'Error: No preset selected.',
		'f1.tab2.section.presets.load.select' => 'Choose a previously saved preset:',
		'f1.tab2.section.presets.save' => 'Save preset:',
		'f1.tab2.section.presets.save.created' => 'Preset %s saved.',
		'f1.tab2.section.presets.save.label' => 'Save new preset:',
		'f1.tab2.section.presets.save.name' => 'Name:',
		'f1.tab2.section.presets.save.notOwner' => 'Error: You are not the owner of this preset.',
		'f1.tab2.section.presets.save.public' => 'Publicly available:',
		'f1.tab2.section.presets.save.save' => 'Save',
		'f1.tab2.section.storageFolder' => 'Storage Folder',
		'f1.tab2.section.storageFolder.error' => 'Error: No storage folder selected!',
		'f1.tab2.section.storageFolder.label' => 'Please select the storage folder for the imported users:',
		'f1.tab2.section.uniqueIdentifier.error' => 'Error: No uniqueIdentifier selected!',
		'f1.tab2.section.uniqueIdentifier.label' => 'Specify the field which determines the uniqueness of imported users:',
		'f1.tab2.section.userType' => 'User type',
		'f1.tab2.section.userType.label' => 'Which type of TYPO3 users do you want to import:',
		'f1.tab3' => 'Field mapping',
		'f1.tab3.description' => 'Please map CSV to DB data fields. You have to map at least a username and password field and all other fields you marked as mandatory..',
		'f1.tab3.mapper' => 'Field mapping',
		'f1.tab3.mapper.auto' => 'AV',
		'f1.tab3.mapper.description' => 'Description',
		'f1.tab3.mapper.field' => 'Field',
		'f1.tab3.mapper.fieldset1' => 'Field mapping',
		'f1.tab3.mapper.fieldset2' => 'Please review your field mapping',
		'f1.tab3.mapper.fieldset2.error' => 'Field mapping error',
		'f1.tab3.mapper.fieldset2.field' => 'Field_',
		'f1.tab3.mapper.import' => 'Update and Preview',
		'f1.tab3.mapper.mapping' => 'Mapping',
		'f1.tab3.mapper.mapsTo' => 'Maps to...',
		'f1.tab3.mapper.message.allMandatoryNo' => ', <strong>but not all mandatory fields mapped.</strong>',
		'f1.tab3.mapper.message.allMandatoryYes' => 'and all mandatory fields mapped.<br /> <strong>You may now proceed with the import or continue to map more fields.</strong>',
		'f1.tab3.mapper.message.error' => 'please review your field mapping for',
		'f1.tab3.mapper.message.info' => 'Mapped %s out of %s fields, %s unique ',
		'f1.tab3.mapper.message.provideMandatory' => ' - please provide mapping for the following mandatory field(s):',
		'f1.tab3.mapper.values' => 'Value',
		'f1.tab4' => 'CSV Import',
		'f1.tab4.description' => 'Ends the workflow by importing the given CSV file to the database.',
		'f1.tab4.section.import' => 'Import CSV file',
		'f1.tab4.section.import.import' => 'IMPORT',
		'f1.tab4.section.import.label' => 'All necessary information for the import process have been entered.<br />By clicking on the <strong>Import</strong> button below, you end the import workflow and the CSV file is read into the database.<br />Import errors are displayed in the <em>Messages</em> tab.<br /> From here you may also go back to the <em>Field mapping</em> tab and correct your settings.<br /><br /><strong>Attention:</strong> By clicking <strong>Import</strong> you actually end the workflow, i.e. all mapping data and import settings are lost beyond this point. <strong>It might be a good idea to save your settings as a preset!</strong>',
		'f1.tab4.section.import.sure' => 'Do you really want to import this file?',
		'f1.tab5' => 'Errors and Messages',
		'f1.tab5.corrected.UCP' => 'corrected uppercase in password',
		'f1.tab5.corrected.UCU' => 'corrected uppercase in username',
		'f1.tab5.corrected.WSP' => 'corrected whitespace in password',
		'f1.tab5.corrected.WSU' => 'corrected whitespace in username',
		'f1.tab5.corrected.renamed' => 'renamed user',
		'f1.tab5.description' => 'Displays import messages and import errors.',
		'f1.tab5.downloadFile' => 'Download drop file (Right-click, save as...)',
		'f1.tab5.error' => 'Fatal Error: ',
		'f1.tab5.error.duplicateUserName' => 'username already exists',
		'f1.tab5.error.emptyMandatory' => 'empty %s',
		'f1.tab5.error.emptyPassword' => 'empty password',
		'f1.tab5.error.emptyUserName' => 'empty username',
		'f1.tab5.error.passwordTooLong' => 'username too long',
		'f1.tab5.error.UCP' => 'uppercase in password',
		'f1.tab5.error.UCU' => 'uppercase in username',
		'f1.tab5.error.unknownFatalError' => 'Unknown fatal error...',
		'f1.tab5.error.userNameTooLong' => 'username too long',
		'f1.tab5.error.WSP' => 'whitespace in password',
		'f1.tab5.error.WSU' => 'whitespace in username',
		'f1.tab5.userInserted' => 'Imported %s (%s) as user with UID %s.',
		'f1.tab5.userUpdated' => 'Updated user %s [UID %s].',
		'f1.tab5.usersImported' => '%s users read, %s new, %s upated, %s skipped.',
		'f1.tab5.userSkipped' => 'User %s [UID %s] skipped: ',
		'f1.tab5.warning' => 'Warning: ',
		'f2.date' => 'Date',
		'f2.importedBy' => 'Imported by:',
		'f2.importedBy.deleted' =>'Deleted user',
		'f2.importedBy.unknown' =>'Unknown user',
		'f2.importFile' => 'Import file:',
		'f2.importSummary' => 'Import Summary',
		'f2.noSessionFound' => 'No active import sessions found...',
		'f2.rollback.sure' => 'Do you really want to roll back this import session? This cannot be undone!!!',
		'f2.sampleData' => 'Sample data of imported users:',
		'f2.session' => 'Session',
		'f2.sessionExpired' => 'Rollback feature expired (latest possible rollback time was <strong><font color="#cc0000">%s</font></strong>)',
		'f2.sessionRollback' => 'Import may be rolled back until <strong><font color="#00aa00">%s</font></strong>.',
		'f2.sessionRolledBack' => 'Session expired or already rolled back.',
		'f2.status' => 'Rollback Status',
		'f2.title' => 'Description',
		'f2.unknownError' => 'Unknown error.',
		'f2.userAlreadyDeleted' => 'User with UID %s already deleted.',
		'f2.usersDropped' => 'Users dropped:',
		'f2.usersImported' => 'Users imported:',
		'f2.usersUpdated' => 'Users updated:',		
		'f2.userType' => 'User type:',
		'f3.securityNote' => 'Security Note',
		'f3.securityNote.message' => '<p>Before you use the import tool please make sure that you have really <strong>understood</strong> all available safety timers and rollback settings:</p><br /><p><strong>Rollback - Safety Timespan:</strong> sets the timespan [in minutes] in which you may rollback previous import sessions. After that you are <em>no longer</em> able to do so and import sessions are only displayed in the overview. You may disable this safety setting by entering a value of 0. THIS IS NOT RECOMMENDED AT ALL</p><br /><p><strong>Garbage Collection - Trigger Timer:</strong> after this timespan [in days] aged out import sessions get deleted (along with all involved import and temporary files) and are no longer displayed in the overview. You may disable the garbage collection by setting this value to 0.</p><br /><p><strong>Rollback - Delete DB Records:</strong> determines whether previously imported users get <em>physically deleted</em> during a rollback or just get <em>marked deleted</em>. TYPO3 usernames must be unique and even if you won\'t see marked deleted users, they are still present in the DB - hence you cannot use such a username!</p><br /><p align="center"><b>If you are still uncertain about any of these settings please read the corresponding section in the extension manual! You have been warned.</b></p>',
	),
	'dk' => Array (
	),
	'de' => Array (
		'title' => 'TYPO3 Benutzer aus CSV Datei importieren',
		'function1' => 'Benutzer Import',
		'function2' => 'Import rückgängig machen',
		'function3' => 'Sicherheitshinweis',
		'f1.tab1' => 'Import Datei',
		'f1.tab1.description' => 'Bitte wählen Sie eine Import-Datei von Ihrem lokalen Rechner aus, die die Benutzerdaten enthält. Die Datei muss in einem lesbaren Format als reine Textdatei vorliegen.',
		'f1.tab1.section.defaultSettings' => 'Allgemeine Einstellungen',
		'f1.tab1.section.importFile' => 'Import Datei',
		'f1.tab1.section.importFile.currentImportFile' => 'Derzeit gewählte Datei:',
		'f1.tab1.section.importFile.emptyImportFile' => '[noch keine Datei ausgewählt]',
		'f1.tab1.section.importFile.importFile' => 'Wählen Sie eine CSV Import Datei von Ihrem lokalen Rechner:',
		'f1.tab1.section.importFile.overwriteFile' => 'Bestehende Dateien überschreiben:',
		'f1.tab1.section.loadSettings' => 'Voreinstellungen laden',
		'f1.tab1.section.error' => 'File upload error',
		'f1.tab1.section.error.description' => 'File upload failed, please review your user settings. Possible reasons for this error: you don\'t have access rights to the upload folder or the folder fileadmin\_temp_ does not exist. Please correct this.',
		'f1.tab2' => 'Import Einstellungen',
		'f1.tab2.constants.BE' => 'BE (Backend Benutzer)',
		'f1.tab2.constants.colon' => 'Doppelpunkt [:]',
		'f1.tab2.constants.comma' => 'Komma [,]',
		'f1.tab2.constants.FE' => 'FE (Frontend Benutzer)',
		'f1.tab2.constants.semicolon' => 'Semikolon [;]',
		'f1.tab2.constants.tab' => 'TAB',
		'f1.tab2.constants.TT' => 'tt_address (Adressen)',
		'f1.tab2.description' => 'Bitte überprüfen Sie die Voreinstellungen für diesen Importvorgang. Wahlweise können Sie aber eine frühere Import-Konfiguration laden.',
		'f1.tab2.section.defaultGroup' => 'Benutzergruppe',
		'f1.tab2.section.defaultGroup.emptyGroup' => '[FEHLER: keine FE Benutzergruppen]',
		'f1.tab2.section.defaultGroup.emptyGroup.error' => 'Fehler: Bitte wählen Sie ein oder mehrere Benutzergruppen aus!',
		'f1.tab2.section.defaultGroup.label' => 'Wählen Sie eine Benutzergruppe für die importierten Benutzer:',
		'f1.tab2.section.generalSettings' => 'Allgemeine Einstellungen',
		'f1.tab2.section.generalSettings.additionalMandatoryFields' => 'Zusätzliche Pflichtfelder',
		'f1.tab2.section.generalSettings.additionalMandatoryFields.description' => 'Wählen Sie zusätzliche Pflichtfelder, die für jeden zu importierenden Benutzer vorhanden sein <em>müssen</em> [STRG gedrückt halten für Mehrfachauswahl]:',
		'f1.tab2.section.generalSettings.enableAutoRename' => 'Auto Rename aktivieren:',
		'f1.tab2.section.generalSettings.enableAutoValues' => 'Enable auto-values :',
		'f1.tab2.section.generalSettings.fieldDelimiter' => 'Trennzeichen zwischen den einzelnen Datenfeldern (Feldtrenner):',
		'f1.tab2.section.generalSettings.fieldEncaps' => 'Datenfelder sind mit diesem Zeichen eingeschlossen:',
		'f1.tab2.section.generalSettings.firstRowHasFieldnames' => 'Erste Datenreihe des CSV Importfiles enthält Feldnamen:',
		'f1.tab2.section.generalSettings.previewNum' => 'Anzahl der Datenreihen für die Vorschau:',
		'f1.tab2.section.generalSettings.update' => 'Einstellungen aktualisieren:',
		'f1.tab2.section.generalSettings.update.update' => 'Update',
		'f1.tab2.section.generalSettings.updateIDField' => 'Select field to detect existing users (also be in mapping):',
		'f1.tab2.section.generalSettings.userupdate' => 'Bereits bestehende Benutzer verändern',
		'f1.tab2.section.generalSettings.userupdate.description' => 'Sollen bereits bestehende Benutzer verändert werden:',
		'f1.tab2.section.presets' => 'Voreinstellungen',
		'f1.tab2.section.presets.delete.deleted' => 'Voreinstellungen %s [UID %s] gelöscht.',
		'f1.tab2.section.presets.delete.noSelection' => 'Fehler: Keine Voreinstellung zum Löschen ausgewählt.',
		'f1.tab2.section.presets.delete.notOwner' => 'Fehler: Sie sind nicht der Besitzer dieser Voreinstellung.',
		'f1.tab2.section.presets.load' => 'Voreinstellungen laden:',
		'f1.tab2.section.presets.load.delete' => 'Löschen',
		'f1.tab2.section.presets.load.delete.sure' => 'Wollen Sie die gespeicherte Voreinstellung wirklich löschen?',
		'f1.tab2.section.presets.load.load' => 'Laden',
		'f1.tab2.section.presets.load.loaded' => 'Voreinstellung %s [UID %s] geladen.',
		'f1.tab2.section.presets.load.noData' => 'Fehler: Die Voreinstellung enthielt keine Daten.',
		'f1.tab2.section.presets.load.noSelection' => 'Fehler: Keine Voreinstellung zum Laden ausgewählt.',
		'f1.tab2.section.presets.load.select' => 'Wählen Sie eine der bereits gespeicherten Voreinstellungen:',
		'f1.tab2.section.presets.save' => 'Voreinstellungen speichern:',
		'f1.tab2.section.presets.save.created' => 'Voreinstellungen %s gespeichert.',
		'f1.tab2.section.presets.save.label' => 'Neue Voreinstellungen speichern:',
		'f1.tab2.section.presets.save.name' => 'Name:',
		'f1.tab2.section.presets.save.notOwner' => 'Fehler: Sie sind nicht der Besitzer dieser Voreinstellung.',
		'f1.tab2.section.presets.save.public' => 'Voreinstellung jedermann zugänglich machen:',
		'f1.tab2.section.presets.save.save' => 'Speichern',
		'f1.tab2.section.storageFolder' => 'Speicherort (Storage Folder)',
		'f1.tab2.section.storageFolder.error' => 'Fehler: kein Speicherort gewählt!!',
		'f1.tab2.section.storageFolder.label' => 'Wählen Sie den Speicherort für die importierten Benutzer:',
		'f1.tab2.section.uniqueIdentifier.error' => 'Error: No uniqueIdentifier selected!',
		'f1.tab2.section.uniqueIdentifier.label' => 'Specify the field which denotes uniqueness in the imported users:',
		'f1.tab2.section.userType' => 'Benutzertyp',
		'f1.tab2.section.userType.label' => 'Welche TYPO3 Benutzerart wollen Sie importieren:',
		'f1.tab3' => 'Feldzuordnung',
		'f1.tab3.description' => 'Bitte ordnen Sie jetzt den möglichen Datenbankfeldern den entsprechenden Werten aus Ihrer Import Datei zu. Sie müssen mindestens einen Benutzernamen und ein Passwort auswählen!',
		'f1.tab3.mapper' => 'Feldzuordnung',
		'f1.tab3.mapper.auto' => 'AW',
		'f1.tab3.mapper.description' => 'Description',
		'f1.tab3.mapper.field' => 'Feld',
		'f1.tab3.mapper.fieldset1' => 'Feldzuordnung',
		'f1.tab3.mapper.fieldset2' => 'Bitte überprüfen Sie die Feldzuordnung',
		'f1.tab3.mapper.fieldset2.error' => 'Zuordnungsfehler',
		'f1.tab3.mapper.fieldset2.field' => 'Feld_',
		'f1.tab3.mapper.import' => 'Überprüfen und Vorschau',
		'f1.tab3.mapper.mapping' => 'Mapping',
		'f1.tab3.mapper.mapsTo' => 'Zuordnung...',
		'f1.tab3.mapper.message.allMandatoryNo' => ', <strong>aber noch nicht alle Pflichtfelder vorhanden.</strong>',
		'f1.tab3.mapper.message.allMandatoryYes' => 'und alle Pflichtfelder vorhanden.<br /> <strong>Sie können jetzt den eigentlichen Importvorgang starten oder noch weitere Feldzuordnungen vornehmen.</strong>',
		'f1.tab3.mapper.message.error' => 'überprüfen Sie bitte nochmals die Feldzuordnungen!',
		'f1.tab3.mapper.message.info' => '%s von %s möglichen Feldern zugeordnet, %s eindeutige Werte ',
		'f1.tab3.mapper.message.provideMandatory' => '- bitte ordnen Sie folgende Pflichtfelder zu:',
		'f1.tab3.mapper.values' => 'Values',
		'f1.tab4' => 'CSV Import',
		'f1.tab4.description' => 'Schliesst den Arbeitsablauf ab und importiert die Benutzer in die Datenbank.',
		'f1.tab4.section.import' => 'CSV Datei importieren',
		'f1.tab4.section.import.import' => 'Importieren',
		'f1.tab4.section.import.label' => 'Alle notwendigen Importeinstellungen sind jetzt vorhanden.<br />Wenn Sie nun auf <strong>Importieren</strong> klicken, werden die in der Datei vorhanden Benutzer in die Datenbank eingefügt und der Importvorgang ist beendet. Sollten dabei Fehler auftreten, werden diese unterhalb des Reiters <em>Meldungen</em> angezeigt.<br /> Sie können aber auch noch weitere Datenfelder zuordnen, indem Sie zum Reiter <em>Feldzuordnung</em> zurückkehren.<br /><strong>Achtung:</strong> Nachdem Sie auf Import geklickt haben, können Sie keinerlei Veränderungen mehr vornehmen! <strong>Speichern Sie jetzt Ihre Einstellungen als neue Voreinstellung, falls Sie noch weitere Importvorgänge starten wollen.</strong>',
		'f1.tab4.section.import.sure' => 'Wollen Sie die Datei wirklich importieren?',
		'f1.tab5' => 'Meldungen und Fehler',
		'f1.tab5.corrected.UCP' => 'Großbuchstaben in Passwort korrigiert',
		'f1.tab5.corrected.UCU' => 'Großbuchstaben in Benutzernamen korrigiert',
		'f1.tab5.corrected.WSP' => 'Leerzeichen in Passwort korrigiert',
		'f1.tab5.corrected.WSU' => 'Leerzeichen in Benutzernamen korrigiert',
		'f1.tab5.corrected.renamed' => 'Benutzer umbenannt.',
		'f1.tab5.description' => 'Meldungen, die während des Importvorgangs aufgetreten sind.',
		'f1.tab5.downloadFile' => 'Datei downloaden (mit Rechtsklick, Speichern unter...)',
		'f1.tab5.error' => 'Fehler:',
		'f1.tab5.error.duplicateUserName' => 'Benutzername exisitiert bereits',
		'f1.tab5.error.emptyMandatory' => 'Pflichtfeld %s leer',
		'f1.tab5.error.emptyPassword' => 'Passwort ist leer',
		'f1.tab5.error.emptyUserName' => 'Benutzername ist leer',
		'f1.tab5.error.passwordTooLong' => 'Passwort zu lang',
		'f1.tab5.error.UCP' => 'Großbuchstaben in Passwort',
		'f1.tab5.error.UCU' => 'Großbuchstaben in Benutzernamen',
		'f1.tab5.error.unknownFatalError' => 'Unbekannter schwerer Fehler...',
		'f1.tab5.error.userNameTooLong' => 'Benutzername zu lang',
		'f1.tab5.error.WSP' => 'Leerzeichen in Passwort',
		'f1.tab5.error.WSU' => 'Leerzeichen in Benutzernamen',
		'f1.tab5.userInserted' => '%s (%s) als Benutzer mit der UID %s importiert.',
		'f1.tab5.userUpdated' => 'User %s [UID %s] aktualisiert.',
		'f1.tab5.usersImported' => '%s Benutzer gelesen, %s neu, %s aktualisiert, %s verworfen.',
		'f1.tab5.userSkipped' => 'Benutzer %s [UID %s] übersprungen: ',
		'f1.tab5.warning' => 'Warnung:',
		'f2.date' => 'Datum',
		'f2.importedBy' => 'Importiert von:',
		'f2.importedBy.deleted' =>'Gelöschter Benutzer',
		'f2.importedBy.unknown' =>'Unbekannter Benutzer',
		'f2.importFile' => 'Import-Datei:',
		'f2.importSummary' => 'Zusammenfassung',
		'f2.noSessionFound' => 'Keine aktiven Importsitzungen gefunden...',
		'f2.rollback.sure' => 'Wollen Sie die Import-Sitzung wirklich rückgängig machen?',
		'f2.sampleData' => 'Beispieldaten importierter Benutzer:',
		'f2.session' => 'Sitzung',
		'f2.sessionExpired' => 'Importvorgang kann nicht mehr rückgängig gemacht werden (letzmöglicher Zeitpunkt war <strong><font color="#cc0000">%s</font></strong>).',
		'f2.sessionRollback' => 'Importvorgang kann bis <strong><font color="#00aa00">%s</font></strong> rückgängig gemacht werden.',
		'f2.sessionRolledBack' => 'Importvorgang wurde bereits rückgängig gemacht.',
		'f2.status' => 'Rollback Status',
		'f2.title' => 'Beschreibung',
		'f2.unknownError' => 'Unbekannter Fehler.',
		'f2.userAlreadyDeleted' => 'Benutzer mit der UID %s wurde bereits gelöscht.',
		'f2.usersDropped' => 'Ignorierte Benutzer:',
		'f2.usersImported' => 'Importierte Benutzer:',
		'f2.usersUpdated' => 'Aktualisierte Benutzer:',		
		'f2.userType' => 'Benutzertyp:',
		'f3.securityNote' => 'Sicherheitshinweis',
		'f3.securityNote.message' => '<p>Bitte vergewissern Sie sich, dass Sie die Bedeutung aller angebotenen Timer  und Rollback Einstellungen <strong>genau</strong> verstanden und entsprechend konfiguriert haben:</p><br /><p><strong>Rollback - Safety Timespan: </strong>gibt die Zeit [in Minuten] an, in welcher Sie den durchgeführten Importvorgang wieder rückgängig machen können. Nach Ablauf dieser Zeitspanne ist <em>kein</em> Rollback mehr möglich und Importvorgänge werden nur noch aufgelistet! 0 deaktiviert diese Sicherheitseinstellung [NICHT EMPFOHLEN]</p><br /><p><strong>Garbage Collection - Trigger Timer:</strong> nach Ablauf dieser Zeitspanne [in Tagen] werden Importvorgänge (mit allen betroffenen Dateien) gelöscht und auch nicht mehr in der Übersicht angezeigt. 0 deaktiviert diese Verhalten und in der Übersicht werden alle Importvorgänge angezeigt.</p><br /><p><strong>Rollback - Delete DB Records:</strong> legt fest, ob bei einem Rollback die zuvor importierten User tatsächlich aus der Datenbank gelöscht oder lediglich als gelöscht markiert werden. Da Benutzernamen eindeutig sein müssen, können als gelöscht markierte Benutzernamen nicht mehr verwendet werden!</p><br /><p align="center"><b>Sollten Ihnen diese Einstellungen immer noch unklar sein, so lesen Sie bitte zuerst nochmal die entsprechenden Abschnitte im Handbuch durch!</b></p>',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>